[package]
authors = ["Fabian Möller <fabianm88@gmail.com>"]
description = "Prometheus exporter reporting ping statistics"
edition = "2021"
keywords = ["prometheus", "prometheus-exporter", "icmp", "ping"]
license = "MIT OR Apache-2.0"
name = "ping-exporter"
readme = "README.md"
repository = "https://github.com/B4dM4n/ping-exporter"
version = "0.1.0"

[dependencies]
anyhow = "1.0.80"
arc-swap = "1.7.0"
axum = { version = "0.7.4", features = ["tracing"] }
clap = { version = "4.5.2", features = ["derive"] }
futures-util = { version = "0.3.30", default-features = false }
hickory-resolver = { version = "0.24.0", features = ["tokio"] }
humantime = "2.1.0"
nix = { version = "0.27.1", features = ["socket"] }
prometheus = { version = "0.13.3", default-features = false, features = ["process"] }
rand = "0.8.5"
surge-ping = "0.8.1"
tokio = { version = "1.36.0", features = ["macros", "signal", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "local-time"] }
