[package]
authors = ["Fabian Möller <fabianm88@gmail.com>"]
description = "Prometheus exporter reporting ping statistics"
edition = "2021"
keywords = ["prometheus", "prometheus-exporter", "icmp", "ping"]
license = "MIT OR Apache-2.0"
name = "ping-exporter"
readme = "README.md"
repository = "https://github.com/B4dM4n/ping-exporter"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
arc-swap = "1.6.0"
clap = { version = "4.4.6", features = ["derive"] }
hickory-resolver = { version = "0.24.0", features = ["tokio"] }
humantime = "2.1.0"
nix = { version = "0.27.1", features = ["socket"] }
prometheus = { version = "0.13.3", default-features = false, features = ["process"] }
rand = "0.8.5"
surge-ping = "0.8.0"
tide = { version = "0.16.0", default-features = false, features = ["h1-server"] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "local-time"] }
